//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Infra.Data.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TabelaSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabelaSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Infra.Data.Sql.TabelaSql", typeof(TabelaSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select cols.COLUMN_NAME as coluna, cons.constraint_type as chaveprimaria
        ///  from all_constraints cons, all_cons_columns cols
        /// where upper(cols.column_name)=upper(:nomecoluna)
        ///   and upper(cols.table_name) =upper(:nometabela)
        ///   and cons.constraint_type = &apos;P&apos;
        ///   and cons.constraint_name = cols.constraint_name
        ///   and cons.owner = cols.owner.
        /// </summary>
        internal static string ObterPrimaryKeyTabelaOracle {
            get {
                return ResourceManager.GetString("ObterPrimaryKeyTabelaOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select tabs.table_name as nome,
        ///       tabs.column_name as coluna,
        ///       tabs.data_type      as tipodado,
        ///       tabs.data_length    as tamanho,
        ///       tabs.nullable       as naonulo,
        ///       tabs.data_scale     as escala,
        ///       cols.comments       as comentario
        ///  from all_tab_columns tabs, all_col_comments cols
        /// where tabs.table_name = cols.table_name
        ///   and tabs.column_name = cols.column_name  
        ///   and tabs.OWNER = cols.OWNER
        ///   and tabs.OWNER = &apos;CENTRALBOLETO&apos;
        ///   and tabs.table_name = :nometa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObterPropriedadeTabelaOracle {
            get {
                return ResourceManager.GetString("ObterPropriedadeTabelaOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select table_name as nome from user_tables order by 1.
        /// </summary>
        internal static string ObterTodasTabelaOracle {
            get {
                return ResourceManager.GetString("ObterTodasTabelaOracle", resourceCulture);
            }
        }
    }
}
